### ISSUE TITLE
Failed to fetch dynamically imported  module

### ISSUE THREAD

**Issue by lordsayur** [lmiller1990/vue-3-cypress-vite#1]
Hi Lachlan,

Im getting error below when running the HelloWorld.spec.js,

```
cypress_runner.js:195896 TypeError: The following error originated from your test code, not from Cypress.

  > Failed to fetch dynamically imported module: http://localhost:3000/__cypress/iframes/C:/Users/Lord%20Sayur/Desktop/vue-3-cypress-vite-master/src/components/HelloWorld.spec.js?import

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
    at Object.runScripts (cypress_runner.js:176955)
    at $Cypress.onSpecWindow (cypress_runner.js:166411)
    at initCypressTests.js:22
```

any idea what caused this error?

**Comment by Schoude** [comment]
Hi @LordSayur,

I ran into the same error and I think I found a solution.

What I found is that it has to do with the **spaces** in the path to the `spec.js` file!

Try putting your project somewhere with no spaces in the full path so they don't get replaced by `%20`. For you, the problematic part is your user folder `Lord%20Sayur`.

This solved the issue for me. Weirdly enough Vite itself has no problems with this.

@lmiller1990 Can you please double-check this behavior and if you can confirm it file a bug report? I am on a Windows machine and LordSayur is as well as it seems from the file path.

Hope this works for you also!
Cheers

**Comment by lmiller1990** [comment]
Hi! Sorry @LordSayur I did not get a notification and missed your original issue report.

We had an issue with white space *way* back, that was fixed a long time ago (on both windows and unix) so if you grab the latest version of everything, it should be all working as expected.

Are you still having this problem @Schoude ? What version of Cypress and `@cypress/vite-dev-server` are you on?

**Comment by lmiller1990** [comment]
Also all the examples are moved here: https://github.com/cypress-io/cypress-component-examples

**Comment by Schoude** [comment]
@lmiller1990 I just checked out the vite-vue part of the cypress component examples and put it in a folder with whitespace as you can see here `http://localhost:3000/__cypress/iframes/E:/webdev/playground/Vue/path%20with%20whitespace/src/components/HelloWorld.spec.js?import` and in the screenshot with the dependencies.

![image](https://user-images.githubusercontent.com/44449464/126992518-8119423e-7193-4c74-b0b0-3f080a3f282a.png)

As you can see I still get the error, even with the dependencies from the newest example. The `E:` drive is not my main drive but I don't know if this could cause such an issue.

After that, I added dashes to the root folder name and tried again. Without the whitespaces in the file path, it again works.

![image](https://user-images.githubusercontent.com/44449464/126993350-9614f560-1fd2-4c97-bbdb-d4cfb868cf00.png)

This is my version of Windows if it helps.
![image](https://user-images.githubusercontent.com/44449464/126993456-8fff07bd-ba57-410d-b0e0-346c267417c3.png)

**Comment by lmiller1990** [comment]
Hi! What version of Cypress have you got? I updated the dependencies 7 days ago (around the time you tried). Is it possible you had the older version with the bug?

**Comment by Schoude** [comment]
I tried it with cypress `7.7.0` and `8.0.0.` In both cases, the removal of the whitespace from the file path fixed the issue.

**Comment by lmiller1990** [comment]
Weird. The white space issue should be fixed. I may need to revisit this - I wonder if it's a windows specific bug (tested on windows, and we have windows running on CI... but may need to be more thorough).

Thanks for the feedback.

**Comment by petegriffith** [comment]
Hi, this still seems to be an issue. There's a folder with whitespaces in my pathname that I can't change (it's my Windows user folder), so I'm hoping there's another workaround. 

Using Cypress `9.2.0`.

**Comment by jdhaines** [comment]
So I was searching for answer to this problem and learned a little more in the process.  I'm also using Vue3 and Vite.  My component tests were in a folder called `__tests__` <- That's a double underscore on each side.  I was getting this same error.  The import that was failing was a "2 level up" type of thing (e.g. `../../css/index.css`.  I didn't have any whitespace anywhere in a file path.  But these double underscores caused the same issue.  Once I renamed the test-containing-folder to `tests` the issue went away.  I'm able to run the tests either by removing all imports or removing underscores from the folder names.

Hope this helps you track down this tricky bug!  I'm using cypress 9.3.1.

**Comment by dkdev030** [comment]
Hi, just found this issue and wanted to report back that this is still a problem. Just wired up a blank Vue 3 Application via cli with cypress. 
The path contains a whitespace, which is my username. Moving the whole directory as others already suggested to a non-whitespace path seems to be the only valid workaround.

Using Cypress `9.5.4` on Windows 10 Enterprise 21H2

**Comment by lmiller1990** [comment]
It is still an issue, I will try to fix it now. 

![image](https://user-images.githubusercontent.com/19196536/167347909-ce69074c-030e-40c9-959d-1b667364b2f4.png)

**Comment by lmiller1990** [comment]
Wonderful, PR incoming.

![image](https://user-images.githubusercontent.com/19196536/167352159-331bd154-7ded-4f40-a9c1-79cc1418b51d.png)

PR: https://github.com/cypress-io/cypress/pull/21386 (hopefully CI passes).

PS if anyone has a deep interest and expertise in this kind of thing, I'm hiring for my team at Cypress. Msg me :) some expertise in Node.js and devtooling is ideal, as well as passion for making better stuff for the component ecosystem.

**Comment by dkdev030** [comment]
Hi @lmiller1990! Just saw your PR and that it passed the CI. Thanks for your fast reply and fix!

Regards.

**Comment by lmiller1990** [comment]
It's out - install the latest `@cypress/vite-dev-server`, you should be good to go.
